---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-argo-0731
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-argo-0731 
  name: test-argo-0731
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi